# Generated by Django 4.1.4 on 2022-12-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='date_showed',
            field=models.CharField(max_length=50),
        ),
    ]
